name: Test Run

on:
  pull_request:
    branches:
      - 2025.1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Create lib directory
      run: mkdir -p lib

    - name: Download JUnit Platform Console Standalone
      run: curl -L -o lib/junit-platform-console-standalone-1.11.4.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.4/junit-platform-console-standalone-1.11.4.jar

    - name: Compile Java code
      run: javac -cp "lib/*" -d bin src/*.java test/*.java

    - name: Run tests
      run: java -jar lib/junit-platform-console-standalone-1.11.4.jar --class-path target --scan-class-path
